"""LLM prompt templates."""

from automic_etl.llm.prompts.templates import (
    SCHEMA_INFERENCE_PROMPT,
    ENTITY_EXTRACTION_PROMPT,
    DATA_CLASSIFICATION_PROMPT,
    QUERY_BUILDER_PROMPT,
    ANOMALY_DETECTION_PROMPT,
    DATA_QUALITY_PROMPT,
)

__all__ = [
    "SCHEMA_INFERENCE_PROMPT",
    "ENTITY_EXTRACTION_PROMPT",
    "DATA_CLASSIFICATION_PROMPT",
    "QUERY_BUILDER_PROMPT",
    "ANOMALY_DETECTION_PROMPT",
    "DATA_QUALITY_PROMPT",
]
